NO_PERMISSION: '&cI''m sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe that this is in error.'
TARGET_NOT_FOUND: '&f[&bGCEffects&f] &7The player you specified could not be found.'
EFFECT_NOT_FOUND: '&f[&bGCEffects&f] &7The &b%effect% &7effect does not exist.'
SENDING_TEST_EFFECT: '&f[&bGCEffects&f] &7Now playing the &b%effect% &7effect to &b%target%&7.'
SENDING_TEST_BLOOD_EFFECT: '&f[&bGCEffects&f] &7Now playing the &b%effect% &7blood effect on &b%target%&7.'
BLOOD_EFFECTS_ENABLED: '&f[&bGCEffects&f] &7You have &aenabled &7your blood effects.'
BLOOD_EFFECTS_DISABLED: '&f[&bGCEffects&f] &7You have &cdisabled &7your blood effects.'
BLOOD_EFFECTS_ENABLED_OTHER: '&f[&bGCEffects&f] &7You have &aenabled &7your blood effects for &b%player%&7.'
BLOOD_EFFECTS_DISABLED_OTHER: '&f[&bGCEffects&f] &7You have &cdisabled &7your blood effects for &b%player%&7.'
EFFECT_LOCKED: '&f[&bGCEffects&f] &7You have not unlocked the &b%effect% &7effect.'
EFFECT_DISABLED: '&f[&bGCEffects&f] &7The &b%effect% &7effect is currently &cdisabled&7.'
EFFECT_ALREADY_ACTIVE: '&f[&bGCEffects&f] &7You already have this effect &aenabled&7.'
EFFECT_ALREADY_ACTIVE_OTHER: '&f[&bGCEffects&f] &b%player% &7already has this effect &aenabled&7.'
BLOOD_EFFECT_SET: '&f[&bGCEffects&f] &7You set &b%effect% &7as your blood effect.'
BLOOD_EFFECT_SET_OTHER: '&f[&bGCEffects&f] &7You set &b%effect% &7as &b%player%''s &7blood effect.'
KILL_EFFECT_SET: '&f[&bGCEffects&f] &7You set &b%effect% &7as your kill effect.'
KILL_EFFECT_SET_OTHER: '&f[&bGCEffects&f] &7You set &b%effect% &7as &b%player%''s &7kill effect.'



ENABLED_EFFECTS:
  NONE: true
  TEST: true
  LIGHTNING: true
  EXPLOSION: true
  FIREWORK: true
  FLAME: true

ENABLED_BLOOD_EFFECTS:
  NONE: true
  TEST: true
  RED: true
  BLUE: true
  YELLOW: true
  FLAME: true
  BEDROCK: true
  TNT: true