name: GCEffects
version: '${project.version}'
main: net.guildcraft.gceffects.GCEffects
authors: [ Frxq15 ]
description: GC Effects Plugin
website: guildcraft.net

commands:
  testeffect:
    usage: /testeffect <player> <effect>
    permission: gceffects.testeffect
  testbloodeffect:
    usage: /testbloodeffect <player> <effect>
    permission: gceffects.testbloodeffect
  togglebloodeffects:
    usage: /togglebloodeffects <player>
    aliases: [togglebe, togglebloodeffect]
    permission: gceffects.togglebloodeffects
  setbloodeffect:
    usage: /setbloodeffect <effect>
    aliases: [setbe]
    permission: gceffects.setbloodeffect
  setkilleffect:
    usage: /setkilleffect <effect>
    aliases: [setke]
    permission: gceffects.setkilleffect